server:
  port: 8090
  tomcat:
    additional-tld-skip-patterns: "*mchange-commons-java*.jar"
spring:
  thymeleaf:
    enabled: true
jdbc:
  driver: com.mysql.cj.jdbc.Driver
  url: jdbc:mysql://localhost:3306/spring_security_demo_bcrypt?useSSL=false&useUnicode=true&serverTimezone=UTC
  user: root
  password: 6799963

connection:
  pool:
    initialPoolSise: 5
    minPoolSize: 5
    maxPoolSize: 20
    maxIdleTime: 3000
